### ISSUE TITLE
Version of Go is out of date

### ISSUE THREAD

**Issue by lmullen** [kmulvey/govulncheck-action#1]
Thanks for creating this. Very useful.

I am getting a vulnerability report on my code via the GitHub action, but not when I run `govulncheck` locally. The vulnerability was fixed in Go 1.19.1, which I am using locally. Reading the logs from the GitHub action, it appears that Go 1.19 (thus. 1.19.0?) is hardcoded into the action. Is it possible to use the latest patch version of whatever version is specified in `go.mod`?

**Comment by WojtekWaga** [comment]
Hey @lmullen it takes the go version that's available. If you are using "actions/setup-go@v2" try this:
   
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.19.1"
          
as this action's behavior is: "take the newest go version there is (unless you have some old crap in your cache then it's good too)"

**Comment by lmullen** [comment]
Brilliant. That works for me. Thank you for explaining it.
